In [25]:
def clean_dict(dictd):
    for i in dictd:
        df = dictd[i]
        df.reset_index(inplace=True)
        headers = df.iloc[0].values
        df.columns = headers
        df.drop(index=0, axis=0, inplace=True)
        dictd[i] = df

In [80]:
import pandas as pd

db = pd.read_excel('databases/Dados EPE/Consumo de Energia por Setor.xlsx', usecols='A:BB').transpose()

dictd_raw = {
    "Setor_Energético": db[0: 17],
    "Setor_Energético_%": db[22: 32]
}

clean_dict(dictd_raw)

def format(string:str, percentage=False):
    words = string.lower().split(' ')
    if percentage:
        words.append("%")
    return "_".join(words)

def format_columns(df, ):
    return df.rename(columns={old_name: format(old_name) for old_name in df.columns})

dictd_raw["Setor_Energético"]

D:\Users\msnc\AppData\Local\Temp\ipykernel_14612\201252592.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(index=0, axis=0, inplace=True)
D:\Users\msnc\AppData\Local\Temp\ipykernel_14612\201252592.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(index=0, axis=0, inplace=True)

,TABELA 3.1.a,SETOR ENERGÉTICO,FONTES,GÁS NATURAL,BAGAÇO DE CANA,ÓLEO DIESEL,BIODIESEL,ÓLEO COMBUSTÍVEL,GÁS LIQUEFEITO DE PETRÓLEO,NAFTA,...,ÓLEO DIESEL,BIODIESEL,ÓLEO COMBUSTÍVEL,GÁS LIQUEFEITO DE PETRÓLEO,QUEROSENE,GÁS CANALIZADO,ELETRICIDADE,CARVÃO VEGETAL,OUTRAS SECUNDÁRIAS DE PETRÓLEO,TOTAL
1,Unnamed: 1,NaN,1970.0,65.093952,89.199155,55.725919,0.0,885.486443,0.0,0.0,...,7.597472,0.0,38.580549,1.839143,0.981246,0.252582,18.352687,0.0,0.0,100.0
2,Unnamed: 2,NaN,1971.0,81.807264,84.089896,53.153954,0.0,933.350575,0.0,0.0,...,6.660003,0.0,44.986687,1.706591,1.728311,0.213416,18.356735,0.0,0.044036,100.0
3,Unnamed: 3,NaN,1972.0,87.9648,73.658491,59.155207,0.0,1099.034109,0.0,0.0,...,5.817718,0.0,45.37678,1.747136,2.248625,0.229432,20.108081,0.0,0.042709,100.0
4,Unnamed: 4,NaN,1973.0,86.205504,129.647459,113.166482,0.0,1334.672913,0.0,0.0,...,4.69893,0.0,55.600938,1.718795,1.978536,0.19348,17.928195,0.0,0.065615,100.0
5,Unnamed: 5,NaN,1974.0,120.511776,125.176857,125.168988,0.0,1409.230503,0.0,0.0,...,4.472529,0.0,55.934241,1.878634,2.122551,0.262537,18.512229,0.0,0.094038,100.0
6,Unnamed: 6,NaN,1975.0,131.067552,138.588663,139.743459,0.0,1520.606656,0.0,0.0,...,4.303598,0.0,55.47794,2.625298,1.889815,0.293271,19.029985,0.0,0.08917,100.0
7,Unnamed: 7,NaN,1976.0,128.428608,115.596996,144.030068,0.0,1643.690503,0.0,0.0,...,4.028754,0.0,56.780814,2.165061,1.971063,0.390887,17.642372,0.0,3.93277,100.0
8,Unnamed: 8,NaN,1977.0,140.74368,563.934515,151.745965,0.0,1712.29508,0.0,0.0,...,4.310786,0.0,53.555057,2.633105,2.093769,0.514154,19.206297,0.0,5.05654,100.0
9,Unnamed: 9,NaN,1978.0,137.225088,1235.802136,158.604539,0.0,1720.753179,0.0,0.0,...,4.278806,0.0,50.323499,2.658138,1.913774,0.579008,23.484317,0.0,5.666451,100.0
10,Unnamed: 10,NaN,1979.0,141.623328,2035.188359,224.618321,0.0,1783.719024,0.0,0.0,...,3.559425,0.0,48.337857,2.433865,2.002255,0.649792,25.760964,0.0,6.361975,100.0
11,Unnamed: 11,NaN,1980.0,165.373824,2012.835349,246.81024,0.0,1784.922239,0.0,0.0,...,2.607303,0.0,50.578272,2.362413,1.546544,0.607557,26.566237,0.192031,5.192082,100.0
12,Unnamed: 12,NaN,1981.0,173.290656,2250.6288,236.212827,0.0,1546.301335,17.437118,0.0,...,5.165309,0.0,36.468344,2.577289,1.838893,0.925858,35.710909,0.259265,0.926643,100.0
13,Unnamed: 13,NaN,1982.0,343.942368,3092.379299,313.19136,0.0,1441.155859,13.700592,0.0,...,2.359971,0.0,38.595806,1.68084,2.546973,0.93625,35.160882,0.352285,0.584122,100.0
14,Unnamed: 14,NaN,1983.0,430.147872,4455.487151,371.949466,0.0,1327.119313,12.380777,0.0,...,2.487655,0.0,30.572665,2.071589,1.673857,1.158207,41.90417,0.577679,0.526902,100.0
15,Unnamed: 15,NaN,1984.0,552.418944,5343.646757,301.435545,0.0,1422.580771,5.57135,10.5552,...,1.957875,0.0,22.26862,2.049176,1.413705,1.230679,44.64282,0.960926,0.348796,100.0
16,Unnamed: 16,NaN,1985.0,801.359328,6709.522124,352.21427,0.0,1413.76963,13.021375,0.0,...,1.682107,0.0,23.130368,2.045692,1.235139,1.149035,44.015073,0.840948,0.128133,100.0